name: prms6-bmi-dev
channels:
  - conda-forge
  - csdms-stack
  - defaults
dependencies:
  - python
  - libnetcdf
  - netcdf-fortran
  - fortran-compiler
  - cmake
  - make
  - coretran
  - numpy
  - matplotlib
  - xarray
  - pandas
  - geopandas
  - descartes
  - requests
  - pymt
  - pymt_prms_surface
  - pymt_prms_soil
  - pymt_prms_groundwater
  - pymt_prms_streamflow
  - prms
