name: prms6-bmi
channels:
  - conda-forge
  - csdms-stack
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - xarray
  - pandas
  - geopandas
  - descartes
  - requests
  - pymt >=1.3
  - pymt_prms_surface
  - pymt_prms_soil
  - pymt_prms_groundwater
  - pymt_prms_streamflow
  - pymt_gridmet
  - prms
